# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# English Setup
en:
  label: "🇬🇧 English"
  contentDir: content/en
  weight: 1
  title: Superconducting Quantum Systems Lab

# French Setup
fr:
  label: "🇫🇷 Français"
  contentDir: content/fr
  weight: 2
  title: Laboratoire de Systèmes Quantiques Supraconducteurs

# Italian Setup
it:
  label: "🇮🇹 Italiano"
  contentDir: content/it
  weight: 3
  title: Laboratorio di Sistemi Quantici Sopraconduttori
